import './globals.css'
import { Inter } from 'next/font/google'
import { Taskprovider } from '@/context/tasksContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Taskprovider>{children}</Taskprovider>
      </body>
    </html>
  );
}
